//Person Group
export const GET_PERSONGROUPS = "GET_PERSONGROUPS";
export const CREATE_PERSONGROUP = "CREATE_PERSONGROUP";
export const UPDATE_PERSONGROUP = "UPDATE_PERSONGROUP";
export const DELETE_PERSONGROUP = "DELETE_PERSONGROUP";

//Person Group Person
export const GET_PERSONGROUP = "GET_PERSONGROUP";
export const GET_PERSONGROUPPERSONS = "GET_PERSONGROUPPERSONS";
export const CREATE_PERSONGROUPPERSON = "CREATE_PERSONGROUP";
export const UPDATE_PERSONGROUPPERSON = "UPDATE_PERSONGROUP";
export const DELETE_PERSONGROUPPERSON = "DELETE_PERSONGROUP"

export const GET_TRAININGSTATUS = "GET_TRAININGSTATUS";
export const CREATE_TRAINING = "CREATE_TRAINING";

//Person Group Person Face

export const GET_PERSON = "GET_PERSON";
export const CREATE_FACE = "CREATE_FACE";
export const UPDATE_FACE = "UPDATE_FACE";
export const DELETE_FACE = "DELETE_FACE"


//Detect / Identify
export const FACE_DETECT = "FACE_DETECT";
export const FACE_IDENTIFY = "FACE_IDENTIFY";